### ISSUE TITLE
Could not find io.openmobilemaps:layer-gps:1.5.1

### ISSUE THREAD

**Issue by ceoy** [geoadmin/lib-open-swiss-maps-sdk#106]
I'm receiving the following exception when trying to build a newly created android project.

`implementation 'ch.admin.geo.openswissmaps:openswissmaps-sdk:1.5.1'` 

```
>Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find io.openmobilemaps:layer-gps:1.5.1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/io/openmobilemaps/layer-gps/1.5.1/layer-gps-1.5.1.pom
       - https://repo.maven.apache.org/maven2/io/openmobilemaps/layer-gps/1.5.1/layer-gps-1.5.1.pom
     Required by:
         project :app > ch.admin.geo.openswissmaps:openswissmaps-sdk:1.5.1
```

**Comment by maurhofer-ubique** [comment]
Hey @ceoy,

Thank you for your report. The [OpenMobileMaps layer-gps](https://github.com/openmobilemaps/layer-gps) module version 1.5.1 was not properly published to Maven Central and therefore not publicly available. The issue has been fixed and the dependency should now be correctly resolved. Please let us know, if that has solved your problem.
