### ISSUE TITLE
openmobilemaps dependency

### ISSUE THREAD

**Issue by FabioMartignoni89** [geoadmin/lib-open-swiss-maps-sdk#21]
Hello,
is it possible to set the openmobilemaps dependency within the Gradle file to update automatically up to the next major version?
This would be useful in order to instantly receive all the library fixes. For example, there are some super important fixes (memory leak and crash).

In the iOS project is already set like that:
`    dependencies: [
        .package(name: "MapCore",
                 url: "https://github.com/openmobilemaps/maps-core.git",
                 .upToNextMajor(from: "1.1.0")),
    ],`

Thank you very much,
Fabio

**Comment by maurhofer-ubique** [comment]
Hi FabioMartignoni89,

Thank you for your input. Currently, we don't have any plans to automate the release of OpenSwissMaps upon updates in OpenMobileMaps. Thus, the OpenSwissMaps releases are done manually when new features or fixes in the module or one of its dependencies are ready or available. 
We plan to release an update in the next days, as well as more often further on, in general.

**Comment by FabioMartignoni89** [comment]
Hi Maurhofer,
thank you for the feedback.

It would be great if you could make a release if/when there are updates about issue #65 in openmobilemaps.
